package dpapps.exchangecurrencyapp.exchange.tools;

/**
 * The class all the currency types available in this application.
 * When more currency types were to be imported, they are first compared with entries of this enum.
 */
public enum AvailableCurrencyTypes {
            EUR,
            USD ,
            JPY ,
            BGN ,
            CYP ,
            CZK ,
            DKK ,
            EEK ,
            GBP ,
            HUF ,
            LTL ,
            LVL ,
            MTL ,
            PLN ,
            ROL ,
            RON ,
            SEK ,
            SIT ,
            SKK ,
            CHF ,
            ISK ,
            NOK ,
            HRK ,
            RUB ,
            TRL ,
            TRY ,
            AUD ,
            BRL ,
            CAD ,
            CNY ,
            HKD ,
            IDR ,
            ILS ,
            INR ,
            KRW ,
            MXN ,
            MYR ,
            NZD ,
            PHP ,
            SGD ,
            THB ,
            ZAR 
}
